# Generated by Django 4.0.2 on 2022-11-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=90, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Projects Section',
            },
        ),
    ]
